version: 2.1

references:
    set_npm_token: &set_npm_token
        run:
            name: Add NPM auth token file
            command: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

jobs:
    build:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run build

            - persist_to_workspace:
                  root: "."
                  paths:
                      - lib

    format:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run format

    install:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-1-{{ checksum "package-lock.json" }}

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-1-{{ checksum "package-lock.json" }}

            - persist_to_workspace:
                  root: "."
                  paths:
                      - ./*
                      - node_modules
                      - package-lock.json
                      - src

    lint:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run lint

    publish:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - *set_npm_token

            - attach_workspace:
                  at: "."

            - run: npm publish || exit 0

    test:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run test

workflows:
    version: 2
    install_and_verify:
        jobs:
            - install
            - build:
                  requires:
                      - install
            - format:
                  requires:
                      - install
            - lint:
                  requires:
                      - install
            - publish:
                  context: My Context
                  filters:
                      branches:
                          only: master
                  requires:
                      - build
                      - format
                      - lint
                      - test
            - test:
                  requires:
                      - install
